# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ECE496' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ECE496
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  target 'ECE496Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ECE496UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
